name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t simple_site .

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: nginx-image
        path: ./simple_site.dockerfile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if package.json exists
      run: |
        if [ -f "simple_site/package.json" ]; then
          echo "package.json found!"
        else
          echo "package.json not found!"
          exit 1
        fi

    - name: Install dependencies
      run: |
        cd simple_site
        npm install

    - name: Run tests
      run: |
        cd simple_site
        npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no user@your-server-ip "cd /path/to/project && git pull origin main && docker-compose up -d"
