name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test SSH connection
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.UBUNTU_VM_IP }}          # IP de la VM
        username: ${{ secrets.UBUNTU_VM_USERNAME }} # Nom d'utilisateur pour SSH
        key: ${{ secrets.UBUNTU_VM_PRIVATE_KEY }}   # Clé privée pour SSH
        port: 22                                    # Port SSH
        script: |
          echo "SSH connection successful!"        # Test de la connexion SSH
